create table if not exists public.notificacoes_responsaveis (
  id bigint generated by default as identity primary key,
  aluno_id text not null,
  aluno_nome text,
  turma text,
  tipo text not null default 'comunicado',
  titulo text not null,
  mensagem text not null,
  origem text,
  lido boolean not null default false,
  criado_em timestamptz not null default now()
);

create index if not exists idx_notificacoes_responsaveis_aluno
on public.notificacoes_responsaveis (aluno_id, criado_em desc);

create table if not exists public.responsaveis_dispositivos (
  id bigint generated by default as identity primary key,
  aluno_id text not null,
  numero_matricula text not null,
  nome_responsavel text,
  push_token text,
  plataforma text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists idx_responsaveis_dispositivos_aluno
on public.responsaveis_dispositivos (aluno_id, ativo);
