create table if not exists public.alunos (
  id uuid default gen_random_uuid() primary key,
  nome text not null,
  turma text not null,
  matricula text not null unique,
  criado_em timestamptz not null default now()
);

alter table public.alunos enable row level security;

-- Permite busca pública por nome ou matrícula (necessário para o primeiro vínculo)
create policy "Permitir busca pública de alunos"
on public.alunos for select
to anon
using (true);

create table if not exists public.notificacoes_responsaveis (
  id bigint generated by default as identity primary key,
  aluno_id text not null,
  aluno_nome text,
  turma text,
  tipo text not null default 'comunicado',
  titulo text not null,
  mensagem text not null,
  origem text,
  lido boolean not null default false,
  criado_em timestamptz not null default now()
);

alter table public.notificacoes_responsaveis enable row level security;

-- Permite que qualquer um leia notificações se souber o aluno_id
-- (Em um app real, isso seria restrito ao dispositivo vinculado)
create policy "Permitir leitura de notificações pelo aluno_id"
on public.notificacoes_responsaveis for select
to anon
using (true);

create table if not exists public.responsaveis_dispositivos (
  id bigint generated by default as identity primary key,
  aluno_id text not null,
  numero_matricula text not null,
  nome_responsavel text,
  push_token text,
  plataforma text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.responsaveis_dispositivos enable row level security;

-- Permite inserir novo vínculo
create policy "Permitir inserção de vínculo"
on public.responsaveis_dispositivos for insert
to anon
with check (true);

-- Permite ler o próprio vínculo
create policy "Permitir leitura de vínculo"
on public.responsaveis_dispositivos for select
to anon
using (true);

create index if not exists idx_alunos_nome on public.alunos (nome);
create index if not exists idx_alunos_matricula on public.alunos (matricula);

create index if not exists idx_notificacoes_responsaveis_aluno
on public.notificacoes_responsaveis (aluno_id, criado_em desc);

create index if not exists idx_responsaveis_dispositivos_aluno
on public.responsaveis_dispositivos (aluno_id, ativo);
