import datetime
from urllib.parse import quote

import pandas as pd
import streamlit as st


HORA_LIMITE = datetime.time(7, 45)
TABELA_ATRASOS = "atrasos_alunos"


def _normalizar_texto(valor):
    return str(valor or "").strip()


def _obter_telefone(aluno):
    candidatos = [
        "telefone_responsavel",
        "telefone_responsável",
        "fone_responsavel",
        "whatsapp_responsavel",
        "whatsapp",
        "telefone",
        "celular",
    ]
    for campo in candidatos:
        telefone = _normalizar_texto(aluno.get(campo))
        if telefone:
            return "".join(ch for ch in telefone if ch.isdigit())
    return ""


def _montar_sql_criacao():
    return """
create table if not exists public.atrasos_alunos (
  id bigint generated by default as identity primary key,
  aluno_id text not null,
  aluno_nome text not null,
  turma text,
  data_atraso date not null default current_date,
  hora_chegada time not null,
  motivo text,
  registrado_por text,
  registrado_em timestamptz not null default now(),
  contato_familia_necessario boolean not null default false,
  contato_familia_realizado boolean not null default false,
  observacao_contato text
);

create index if not exists idx_atrasos_alunos_aluno_data
on public.atrasos_alunos (aluno_id, data_atraso);
""".strip()


def _buscar_alunos(supabase):
    res = supabase.table("alunos").select("*").execute()
    return res.data or []


def _buscar_atrasos(supabase, data_inicio=None, data_fim=None):
    query = supabase.table(TABELA_ATRASOS).select("*").order("data_atraso", desc=True).order("hora_chegada", desc=True)
    if data_inicio:
        query = query.gte("data_atraso", data_inicio.isoformat())
    if data_fim:
        query = query.lte("data_atraso", data_fim.isoformat())
    res = query.execute()
    return res.data or []


def _contar_atrasos_aluno(supabase, aluno_id, data_inicio=None, data_fim=None):
    query = supabase.table(TABELA_ATRASOS).select("id").eq("aluno_id", str(aluno_id))
    if data_inicio:
        query = query.gte("data_atraso", data_inicio.isoformat())
    if data_fim:
        query = query.lte("data_atraso", data_fim.isoformat())
    res = query.execute()
    return len(res.data or [])


def _registrar_atraso(supabase, aluno, data_atraso, hora_chegada, motivo, registrado_por, total_apos_registro):
    dados = {
        "aluno_id": str(aluno.get("id")),
        "aluno_nome": _normalizar_texto(aluno.get("nome")),
        "turma": _normalizar_texto(aluno.get("turma")),
        "data_atraso": data_atraso.isoformat(),
        "hora_chegada": hora_chegada.strftime("%H:%M:%S"),
        "motivo": _normalizar_texto(motivo),
        "registrado_por": _normalizar_texto(registrado_por),
        "contato_familia_necessario": total_apos_registro >= 3,
    }
    supabase.table(TABELA_ATRASOS).insert(dados).execute()


def _mensagem_familia(aluno, total_atrasos):
    nome = _normalizar_texto(aluno.get("nome"))
    turma = _normalizar_texto(aluno.get("turma"))
    return (
        f"Olá, família. Informamos que o(a) estudante {nome}, da turma {turma}, "
        f"registrou {total_atrasos} atrasos na chegada à escola. "
        "Pedimos, por gentileza, que entrem em contato com a coordenação para alinharmos o acompanhamento."
    )


def _exibir_alertas_contato(df_atrasos):
    if df_atrasos.empty:
        return

    if "contato_familia_necessario" not in df_atrasos.columns:
        return
    if "contato_familia_realizado" not in df_atrasos.columns:
        df_atrasos["contato_familia_realizado"] = False

    pendentes = df_atrasos[
        (df_atrasos["contato_familia_necessario"] == True)
        & (df_atrasos["contato_familia_realizado"].fillna(False) == False)
    ]
    if pendentes.empty:
        return

    st.warning(f"{len(pendentes)} registro(s) pedem contato com a família.")
    st.dataframe(
        pendentes[["aluno_nome", "turma", "data_atraso", "hora_chegada"]].rename(
            columns={
                "aluno_nome": "Estudante",
                "turma": "Turma",
                "data_atraso": "Data",
                "hora_chegada": "Chegada",
            }
        ),
        use_container_width=True,
        hide_index=True,
    )


def exibir_atrasos(supabase):
    st.title("Registro de Atrasos")
    st.caption("Use esta tela para registrar estudantes que chegaram após 07h45 e acompanhar quando a família precisa ser acionada.")

    hoje = datetime.date.today()
    inicio_ano = datetime.date(hoje.year, 1, 1)

    try:
        alunos = _buscar_alunos(supabase)
    except Exception as erro:
        st.error(f"Não foi possível carregar a tabela de alunos: {erro}")
        return

    if not alunos:
        st.info("Nenhum aluno encontrado na tabela de alunos.")
        return

    try:
        atrasos_ano = _buscar_atrasos(supabase, inicio_ano, hoje)
    except Exception as erro:
        st.error("A tabela de atrasos ainda não existe ou não está acessível.")
        st.code(_montar_sql_criacao(), language="sql")
        st.caption(f"Detalhe técnico: {erro}")
        return

    df_atrasos = pd.DataFrame(atrasos_ano)
    if df_atrasos.empty:
        df_atrasos = pd.DataFrame(columns=["aluno_id", "aluno_nome", "turma", "data_atraso", "hora_chegada"])

    _exibir_alertas_contato(df_atrasos)

    st.divider()
    st.subheader("Novo atraso")

    alunos_ordenados = sorted(alunos, key=lambda item: (_normalizar_texto(item.get("turma")), _normalizar_texto(item.get("nome"))))
    opcoes = {
        f"{_normalizar_texto(a.get('nome'))} - {_normalizar_texto(a.get('turma'))}": a
        for a in alunos_ordenados
        if a.get("id") and a.get("nome")
    }

    c1, c2 = st.columns([2, 1])
    with c1:
        aluno_label = st.selectbox("Estudante", list(opcoes.keys()))
        aluno = opcoes[aluno_label]
    with c2:
        data_atraso = st.date_input("Data", value=hoje)

    c3, c4, c5 = st.columns([1, 1, 2])
    with c3:
        hora_chegada = st.time_input("Hora de chegada", value=datetime.datetime.now().time().replace(second=0, microsecond=0))
    with c4:
        registrado_por = st.text_input("Registrado por", placeholder="Coordenação")
    with c5:
        motivo = st.text_input("Motivo/observação", placeholder="Opcional")

    total_atual = _contar_atrasos_aluno(supabase, aluno.get("id"), inicio_ano, hoje)
    total_apos_registro = total_atual + 1

    m1, m2, m3 = st.columns(3)
    m1.metric("Atrasos no ano", total_atual)
    m2.metric("Após este registro", total_apos_registro)
    m3.metric("Limite para contato", "3")

    if hora_chegada <= HORA_LIMITE:
        st.info("A hora informada está antes ou exatamente em 07h45. Confirme se este registro deve mesmo ser tratado como atraso.")

    if total_apos_registro >= 3:
        st.warning("Este estudante atingirá 3 ou mais atrasos. A família deve ser acionada.")
        mensagem = _mensagem_familia(aluno, total_apos_registro)
        st.text_area("Mensagem sugerida para WhatsApp/ligação", value=mensagem, height=110)

        telefone = _obter_telefone(aluno)
        if telefone:
            st.link_button("Abrir WhatsApp", f"https://wa.me/55{telefone}?text={quote(mensagem)}", use_container_width=True)
        else:
            st.caption("Não encontrei telefone/WhatsApp do responsável no cadastro deste aluno.")

    if st.button("Registrar atraso", type="primary", use_container_width=True):
        try:
            _registrar_atraso(
                supabase,
                aluno,
                data_atraso,
                hora_chegada,
                motivo,
                registrado_por,
                total_apos_registro,
            )
            st.success("Atraso registrado com sucesso.")
            st.rerun()
        except Exception as erro:
            st.error(f"Erro ao registrar atraso: {erro}")

    st.divider()
    st.subheader("Acompanhamento")

    if df_atrasos.empty:
        st.info("Nenhum atraso registrado neste ano.")
        return

    resumo = (
        df_atrasos.groupby(["aluno_id", "aluno_nome", "turma"], dropna=False)
        .size()
        .reset_index(name="total_atrasos")
        .sort_values(["total_atrasos", "turma", "aluno_nome"], ascending=[False, True, True])
    )

    c_resumo, c_historico = st.columns([1, 1.5], gap="large")
    with c_resumo:
        st.write("**Ranking de atrasos no ano**")
        st.dataframe(
            resumo.rename(
                columns={
                    "aluno_nome": "Estudante",
                    "turma": "Turma",
                    "total_atrasos": "Atrasos",
                }
            )[["Estudante", "Turma", "Atrasos"]],
            use_container_width=True,
            hide_index=True,
        )

    with c_historico:
        st.write("**Últimos registros**")
        historico = df_atrasos.sort_values(["data_atraso", "hora_chegada"], ascending=[False, False]).head(50)
        st.dataframe(
            historico.rename(
                columns={
                    "aluno_nome": "Estudante",
                    "turma": "Turma",
                    "data_atraso": "Data",
                    "hora_chegada": "Chegada",
                    "motivo": "Observação",
                    "registrado_por": "Registrado por",
                }
            )[["Estudante", "Turma", "Data", "Chegada", "Observação", "Registrado por"]],
            use_container_width=True,
            hide_index=True,
        )
