import datetime
from urllib.parse import quote
from zoneinfo import ZoneInfo

import pandas as pd
import streamlit as st
from fpdf import FPDF

try:
    from modulos.fotograma_aba import limpar_texto, listar_fotos_github
except Exception:
    limpar_texto = None
    listar_fotos_github = None


HORA_LIMITE = datetime.time(7, 45)
TABELA_ATRASOS = "atrasos_alunos"
FUSO_ESCOLA = ZoneInfo("America/Fortaleza")


def _normalizar_texto(valor):
    return str(valor or "").strip()


def _obter_telefone(aluno):
    candidatos = [
        "telefone_responsavel",
        "telefone_responsável",
        "fone_responsavel",
        "whatsapp_responsavel",
        "whatsapp",
        "telefone",
        "celular",
    ]
    for campo in candidatos:
        telefone = _normalizar_texto(aluno.get(campo))
        if telefone:
            return "".join(ch for ch in telefone if ch.isdigit())
    return ""


def _obter_foto(aluno):
    if listar_fotos_github and limpar_texto:
        try:
            mapa_fotos = listar_fotos_github()
            chave = limpar_texto(aluno.get("nome"))
            foto_github = mapa_fotos.get(chave)
            if isinstance(foto_github, str) and foto_github.startswith("http"):
                return foto_github
        except Exception:
            pass

    candidatos = ["foto", "foto_url", "url_foto", "imagem", "imagem_url", "avatar", "avatar_url"]
    for campo in candidatos:
        foto = _normalizar_texto(aluno.get(campo))
        if foto:
            return foto
    return ""


def _formatar_data_br(valor):
    if not valor:
        return ""
    try:
        return pd.to_datetime(valor).strftime("%d/%m/%Y")
    except Exception:
        return str(valor)


def _formatar_hora_br(valor):
    if not valor:
        return ""
    try:
        return pd.to_datetime(str(valor)).strftime("%H:%M")
    except Exception:
        partes = str(valor).split(":")
        return ":".join(partes[:2]) if len(partes) >= 2 else str(valor)


def _periodo_semana(data_ref):
    inicio = data_ref - datetime.timedelta(days=data_ref.weekday())
    fim = inicio + datetime.timedelta(days=6)
    return inicio, fim


def _gerar_pdf_atrasados(data_ref, registros):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", "B", 14)
    pdf.cell(190, 10, "Registro de Estudantes Atrasados", ln=True, align="C")
    pdf.set_font("Arial", "", 10)
    pdf.cell(190, 8, f"Data: {data_ref.strftime('%d/%m/%Y')}", ln=True, align="C")
    pdf.ln(4)

    pdf.set_font("Arial", "B", 9)
    pdf.cell(75, 8, "Estudante", 1)
    pdf.cell(25, 8, "Turma", 1)
    pdf.cell(25, 8, "Chegada", 1)
    pdf.cell(65, 8, "Observacao", 1, ln=True)

    pdf.set_font("Arial", "", 8)
    if registros.empty:
        pdf.cell(190, 8, "Nenhum atraso registrado.", 1, ln=True)
    else:
        for _, row in registros.iterrows():
            nome = str(row.get("aluno_nome", ""))[:42]
            turma = str(row.get("turma", ""))[:12]
            chegada = _formatar_hora_br(row.get("hora_chegada"))
            motivo = str(row.get("motivo", "") or "")[:38]
            pdf.cell(75, 8, nome, 1)
            pdf.cell(25, 8, turma, 1)
            pdf.cell(25, 8, llegada, 1)
            pdf.cell(65, 8, motivo, 1, ln=True)

    return pdf.output(dest="S").encode("latin-1", errors="replace")


def _preparar_datas_df(df):
    if df.empty or "data_atraso" not in df.columns:
        return df
    df = df.copy()
    df["data_atraso_dt"] = pd.to_datetime(df["data_atraso"], errors="coerce")
    return df


def _montar_sql_criacao():
    return """
create table if not exists public.atrasos_alunos (
  id bigint generated by default as identity primary key,
  aluno_id text not null,
  aluno_nome text not null,
  turma text,
  data_atraso date not null default current_date,
  hora_chegada time not null,
  motivo text,
  registrado_por text,
  registrado_em timestamptz not null default now(),
  contato_familia_necessario boolean not null default false,
  contato_familia_realizado boolean not null default false,
  observacao_contato text
);

create index if not exists idx_atrasos_alunos_aluno_data
on public.atrasos_alunos (aluno_id, data_atraso);
""".strip()


def _buscar_alunos(supabase):
    res = supabase.table("alunos").select("*").execute()
    return res.data or []


def _buscar_atrasos(supabase, data_inicio=None, data_fim=None):
    query = supabase.table(TABELA_ATRASOS).select("*").order("data_atraso", desc=True).order("hora_chegada", desc=True)
    if data_inicio:
        query = query.gte("data_atraso", data_inicio.isoformat())
    if data_fim:
        query = query.lte("data_atraso", data_fim.isoformat())
    res = query.execute()
    return res.data or []


def _contar_atrasos_aluno(supabase, aluno_id, data_inicio=None, data_fim=None):
    query = supabase.table(TABELA_ATRASOS).select("id").eq("aluno_id", str(aluno_id))
    if data_inicio:
        query = query.gte("data_atraso", data_inicio.isoformat())
    if data_fim:
        query = query.lte("data_atraso", data_fim.isoformat())
    res = query.execute()
    return len(res.data or [])


def _contar_no_df(df_atrasos, aluno_id, data_inicio, data_fim):
    if df_atrasos.empty or "data_atraso_dt" not in df_atrasos.columns:
        return 0
    aluno_id = str(aluno_id)
    filtrado = df_atrasos[
        (df_atrasos["aluno_id"].astype(str) == aluno_id)
        & (df_atrasos["data_atraso_dt"] >= pd.Timestamp(data_inicio))
        & (df_atrasos["data_atraso_dt"] <= pd.Timestamp(data_fim))
    ]
    return len(filtrado)


def _registrar_atraso(supabase, aluno, data_atraso, hora_chegada, motivo, registrado_por, total_apos_registro):
    dados = {
        "aluno_id": str(aluno.get("id")),
        "aluno_nome": _normalizar_texto(aluno.get("nome")),
        "turma": _normalizar_texto(aluno.get("turma")),
        "data_atraso": data_atraso.isoformat(),
        "hora_chegada": hora_chegada.strftime("%H:%M:%S"),
        "motivo": _normalizar_texto(motivo),
        "registrado_por": _normalizar_texto(registrado_por),
        "contato_familia_necessario": total_apos_registro >= 3,
    }
    try:
        supabase.table(TABELA_ATRASOS).insert(dados).execute()
    except Exception:
        # Segunda tentativa caso a coluna aluno_nome não exista na tabela do banco
        if "aluno_nome" in dados:
            del dados["aluno_nome"]
            supabase.table(TABELA_ATRASOS).insert(dados).execute()


def _criar_notificacao_atraso(supabase, aluno, hora_chegada, total_apos_registro):
    nome = _normalizar_texto(aluno.get("nome"))
    if total_apos_registro >= 3:
        titulo = "Atenção: limite de atrasos atingido"
        mensagem = (
            f"O(a) estudante {nome} chegou atrasado(a) hoje às {hora_chegada.strftime('%H:%M')} "
            f"e atingiu {total_apos_registro} atrasos no ano. A coordenação solicita acompanhamento da família."
        )
    else:
        titulo = "Chegada com atraso"
        mensagem = (
            f"O(a) estudante {nome} chegou atrasado(a) hoje às {hora_chegada.strftime('%H:%M')}. "
            f"Total de atrasos no ano: {total_apos_registro}."
        )
    
    # Dicionário enxuto para evitar erros de colunas inexistentes na tabela de notificações
    dados = {
        "aluno_id": str(aluno.get("id")),
        "tipo": "atraso",
        "titulo": titulo,
        "mensagem": mensagem
    }
    supabase.table("notificacoes_responsaveis").insert(dados).execute()


def _mensagem_familia(aluno, total_atrasos):
    nome = _normalizar_texto(aluno.get("nome"))
    turma = _normalizar_texto(aluno.get("turma"))
    return (
        f"Olá, família. Informamos que o(a) estudante {nome}, da turma {turma}, "
        f"registrou {total_atrasos} atrasos na chegada à escola. "
        "Pedimos, por gentileza, que entrem em contato com a coordenação para alinharmos o acompanhamento."
    )


def _exibir_alertas_contato(df_atrasos):
    if df_atrasos.empty or "contato_familia_necessario" not in df_atrasos.columns:
        return
    if "contato_familia_realizado" not in df_atrasos.columns:
        df_atrasos = df_atrasos.copy()
        df_atrasos["contato_familia_realizado"] = False

    pendentes = df_atrasos[
        (df_atrasos["contato_familia_necessario"] == True)
        & (df_atrasos["contato_familia_realizado"].fillna(False) == False)
    ]
    if pendentes.empty:
        return

    tabela = pendentes.copy()
    tabela["Data"] = tabela["data_atraso"].apply(_formatar_data_br)
    tabela["Chegada"] = tabela["hora_chegada"].apply(_formatar_hora_br)

    st.warning(f"{len(pendentes)} registro(s) pedem contato com a família.")
    st.dataframe(
        tabela.rename(columns={"aluno_nome": "Estudante", "turma": "Turma"})[["Estudante", "Turma", "Data", "Chegada"]],
        use_container_width=True,
        hide_index=True,
    )


def exibir_atrasos(supabase):
    st.title("Registro de Atrasos")
    st.caption("Registro rápido para estudantes que chegaram após 07h45.")

    agora = datetime.datetime.now(FUSO_ESCOLA)
    hoje = agora.date()
    hora_chegada = agora.time().replace(second=0, microsecond=0)
    inicio_ano = datetime.date(hoje.year, 1, 1)
    inicio_mes = datetime.date(hoje.year, hoje.month, 1)
    inicio_semana, fim_semana = _periodo_semana(hoje)

    try:
        alunos = _buscar_alunos(supabase)
    except Exception as erro:
        st.error(f"Não foi possível carregar a tabela de alunos: {erro}")
        return

    if not alunos:
        st.info("Nenhum aluno encontrado na tabela de alunos.")
        return

    try:
        atrasos_ano = _buscar_atrasos(supabase, inicio_ano, hoje)
    except Exception as erro:
        st.error("A tabela de atrasos ainda não existe ou não está acessível.")
        st.code(_montar_sql_criacao(), language="sql")
        st.caption(f"Detalhe técnico: {erro}")
        return

    df_atrasos = pd.DataFrame(atrasos_ano)
    if df_atrasos.empty:
        df_atrasos = pd.DataFrame(columns=["aluno_id", "aluno_nome", "turma", "data_atraso", "hora_chegada"])
    df_atrasos = _preparar_datas_df(df_atrasos)

    _exibir_alertas_contato(df_atrasos)

    st.divider()
    st.subheader("Novo atraso")

    turmas = sorted({_normalizar_texto(a.get("turma")) for a in alunos if _normalizar_texto(a.get("turma"))})
    if not turmas:
        st.info("Nenhuma turma encontrada no cadastro de alunos.")
        return

    registrado_por = st.selectbox("Identifique-se", ["LYLIAN CABRAL", "LOURENÇA MUNIZ"])

    c_turma, c_data, c_hora = st.columns([1.4, 0.8, 0.8])
    with c_turma:
        turma_sel = st.selectbox("Turma", turmas)
    with c_data:
        st.text_input("Data", value=hoje.strftime("%d/%m/%Y"), disabled=True)
    with c_hora:
        st.text_input("Hora de chegada", value=hora_chegada.strftime("%H:%M"), disabled=True)

    alunos_filtrados = [
        a for a in alunos
        if _normalizar_texto(a.get("turma")) == turma_sel and a.get("id") and a.get("nome")
    ]
    alunos_ordenados = sorted(alunos_filtrados, key=lambda item: _normalizar_texto(item.get("nome")))
    opcoes = {_normalizar_texto(a.get("nome")): a for a in alunos_ordenados}

    if not opcoes:
        st.info("Nenhum aluno encontrado para esta turma.")
        return

    c_aluno, c_foto = st.columns([2.3, 1])
  
    with c_aluno:
        aluno_label = st.selectbox("Estudante", list(opcoes.keys()))
        aluno = opcoes[aluno_label]
        motivo = st.text_input("Motivo/observação", placeholder="Opcional")
    with c_foto:
        foto = _obter_foto(aluno)
        if foto:
            st.markdown(
                f"""
                <div style="text-align:center;">
                    <img src="{foto}" style="width:88px; height:88px; object-fit:cover; border-radius:10px; border:1px solid #d1d5db;">
                    <div style="font-size:11px; line-height:1.1; margin-top:4px;">{_normalizar_texto(aluno.get("nome"))[:28]}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        else:
            st.info("Sem foto cadastrada.")

    total_semana = _contar_no_df(df_atrasos, aluno.get("id"), inicio_semana, fim_semana)
    total_mes = _contar_no_df(df_atrasos, aluno.get("id"), inicio_mes, hoje)
    total_ano = _contar_atrasos_aluno(supabase, aluno.get("id"), inicio_ano, hoje)
    total_apos_registro = total_ano + 1
    atrasos_restantes = max(0, 3 - total_apos_registro)

    indicadores = pd.DataFrame(
        [
            {"Indicador": "ATRS SEMANA", "Valor": total_semana, "Indicador ": "ATRS MÊS", "Valor ": total_mes},
            {"Indicador": "ATRS ATUAIS", "Valor": total_apos_registro, "Indicador ": "ATRS RESTANTES", "Valor ": atrasos_restantes},
        ]
    )
    st.dataframe(indicadores, use_container_width=True, hide_index=True)

    if hora_chegada <= HORA_LIMITE:
        st.info("O horário atual está antes ou exatamente em 07h45. Confirme se este registro deve mesmo ser tratado como atraso.")

    if atrasos_restantes == 0:
        st.error("INFORMAR OS PAIS: este estudante atingiu o limite de 3 atrasos.")
        mensagem = _mensagem_familia(aluno, total_apos_registro)
        st.text_area("Mensagem sugerida para WhatsApp/ligação", value=mensagem, height=110)

        telefone = _obter_telefone(aluno)
        if telefone:
            st.link_button("Abrir WhatsApp", f"https://wa.me/55{telefone}?text={quote(mensagem)}", use_container_width=True)
        else:
            st.caption("Não encontrei telefone/WhatsApp do responsável no cadastro deste aluno.")

    # ---------------------------------------------------------
    # BLOCO INTELIGENTE E RESILIENTE CONTRA FALHAS DE COLUNA
    # ---------------------------------------------------------
    if st.button("Registrar atraso", type="primary", use_container_width=True):
        nome_aluno = _normalizar_texto(aluno.get("nome"))
        atraso_salvo = False
        
        # Passo 1: Tenta registrar o atraso de forma isolada
        try:
            _registrar_atraso(
                supabase,
                aluno,
                hoje,
                hora_chegada,
                motivo,
                registrado_por,
                total_apos_registro,
            )
            atraso_salvo = True
        except Exception as erro_atraso:
            st.error(f"⚠️ Erro crítico ao salvar o atraso no banco de dados: {erro_atraso}")
            
        # Passo 2: Se o atraso foi salvo, tenta enviar a notificação para o app da família
        if atraso_salvo:
            try:
                _criar_notificacao_atraso(supabase, aluno, hora_chegada, total_apos_registro)
                st.success(f"Atraso de {nome_aluno} registado e família notificada com sucesso!")
                st.rerun()
            except Exception as erro_notif:
                # Se a notificação falhar por causa de colunas, o atraso NÃO é perdido!
                st.success(f"Atraso de {nome_aluno} foi gravado com sucesso!")
                st.warning(f"⚠️ Nota: O mural da família não pôde ser atualizado automaticamente (Detalhe: {erro_notif}).")
                if st.button("Atualizar Tela"):
                    st.rerun()

    st.divider()
    st.subheader("Acompanhamento")

    if df_atrasos.empty:
        st.info("Nenhum atraso registrado neste ano.")
        return

    resumo = (
        df_atrasos.groupby(["aluno_id", "aluno_nome", "turma"], dropna=False)
        .size()
        .reset_index(name="total_atrasos")
        .sort_values(["total_atrasos", "turma", "aluno_nome"], ascending=[False, True, True])
    )

    c_resumo, c_historico = st.columns([1, 1.5], gap="large")
    with c_resumo:
        st.write("**Ranking de atrasos no ano**")
        st.dataframe(
            resumo.rename(columns={"aluno_nome": "Estudante", "turma": "Turma", "total_atrasos": "Atrasos"})[
                ["Estudante", "Turma", "Atrasos"]
            ],
            use_container_width=True,
            hide_index=True,
        )

    with c_historico:
        st.write("**Últimos registros**")
        historico = df_atrasos.sort_values(["data_atraso", "hora_chegada"], ascending=[False, False]).head(50).copy()
        historico["Data"] = historico["data_atraso"].apply(_formatar_data_br)
        historico["Chegada"] = historico["hora_chegada"].apply(_formatar_hora_br)
        st.dataframe(
            historico.rename(
                columns={
                    "aluno_nome": "Estudante",
                    "turma": "Turma",
                    "motivo": "Observação",
                    "registrado_por": "Registrado por",
                }
            )[["Estudante", "Turma", "Data", "Chegada", "Observação", "Registrado por"]],
            use_container_width=True,
            hide_index=True,
        )

    registros_hoje = df_atrasos[df_atrasos["data_atraso_dt"].dt.date == hoje].copy()
    pdf_atrasados = _gerar_pdf_atrasados(hoje, registros_hoje)
    st.download_button(
        "Gerar PDF com os atrasados de hoje",
        data=pdf_atrasados,
        file_name=f"atrasados_{hoje.strftime('%d_%m_%Y')}.pdf",
        mime="application/pdf",
        use_container_width=True,
    )