# ==========================================
# 🏠 PROJETO 1: SIGEREMPAM (ALUNOS E CHAMADA)
# ==========================================
SUPABASE_URL_ALUNOS="https://ykbwrfstozvvreuoloxg.supabase.co"
SUPABASE_KEY_ALUNOS="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrYndyZnN0b3p2dnJldW9sb3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMDI3NzQsImV4cCI6MjA4NTg3ODc3NH0.mC8vanbKYCg-JjhVj01STA-z31VgEQ_3drPY8fXFHdE"

# ==========================================
# 📝 PROJETO 2: AVALIADOR (QUESTÕES E PROVAS)
# ==========================================
SUPABASE_URL_PROVAS="https://htidalgkwdnjyclojyqy.supabase.co"
SUPABASE_KEY_PROVAS="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0aWRhbGdrd2RuanljbG9qeXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1OTQ5MDEsImV4cCI6MjA4OTE3MDkwMX0.cIuPYYx32ePFdRvQXD4Kn6pXS77jvoHezBwmmrmDlZ8"